-name: 'gcr.io/cloud-builders/gcloud'
 args:
 —functions
 —deploy=helloGET
 ——runtime=nodejs8
 ——trigger-http
 ——source=./ # Function source files
 ——entry-point=helloGET # Function entry point
 —helloGET # Function name
